<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Please activate your account' => 'Пожалуйста, активируйте ваш аккаунт',
    'A letter for activation was sent to {email}' => 'Письмо для активации было отправлено на {email}',
    'Access Denied' => 'Доступ запрещен',
    'An error occurred while confirming' => 'Произошла ошибка во время подтверждения',
    'An error occurred while saving authItem' => 'Произошла ошибка по время сохранения прав',
    'An error occurred while saving profile' => 'Произошла ошибка во время сохранения профиля',
    'An error occurred while saving user' => 'Произошла ошибка во время сохранения пользователя',
    'An error occurred while sending a message to activate account' => 'Произошла ошибка при отправки письма для активации аккаунта',
    'An error occurred while sending a message to reset password' => 'Произошла ошибка во время отправки письма для сброса пароля',
    'File types' => 'Типы файлов',
    'Image size' => 'Размер картинки',
    'Incorrect email or password' => 'Неверный email или пароль',
    'Incorrect file format' => 'Неверный формат файла',
    'Invalid link for reset password' => 'Неверная ссылка для сброса пароля',
    'Invalid token for activate account' => 'Неверный ключ для активации аккаунта',
    'Max. file number' => 'Макс. кол-во файлов',
    'Max. file size' => 'Макc. размер файла',
    'Max. height' => 'Макc. высота',
    'Max. size of image' => 'Макc. размер картинки',
    'Max. width' => 'Макc. ширина',
    'Min. height' => 'Мин. высота',
    'Min. size of image' => 'Мин. размер картинки',
    'Min. width' => 'Мин. ширина',
    'New password was saved' => 'Новый пароль сохранен',
    'Only latin letters' => 'Только латинские буквы',
    'Page not found' => 'Страница не найдена',
    'Please activate your account. A letter for activation was sent to {email}' => 'Пожалуйста, активируйте ваш аккаунт. Письмо для активации было отправлено на {email}',
    'Saved successfully' => 'Сохранено успешно',
    'There is no user with such email' => 'Пользователя с таким email не существует',
    'This email address has already been taken' => 'Данный email уже занят',
    'To complete the registration process, you must activate your account' => 'Для завершения процесса регистрации необходимо активировать ваш аккаунт',
    'User not found' => 'Пользователь не найден',
    'We sent you a letter on {email}' => 'Мы отправили вам письмо на {email}',
    'We\'ve sent you an email with instructions to reset your password' => 'Мы отправили вам письмо с инструкцией для восстановления пароля',
    'Your account is successfully activated' => 'Ваш аккаунт успешно активирован',
];
