<?php // @codingStandardsIgnoreFile
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A letter for activation was sent to {email}' => 'Письмо для активации было отправлено на {email}',
    'Access Denied' => 'Доступ закрыт',
    'Access is unauthorized' => 'Требуется аутентификация',
    'Account not activated' => 'Аккаунт не активирован',
    'Activate Your Account' => 'Активируйте ваш аккаунт',
    'An error occurred while activating account' => 'Произошла ошибка при активации аккаунта',
    'An error occurred while sending a message to activate account' => 'Произошла ошибка при отправки письма для активации аккаунта',
    'An error occurred while sending a message to reset your password' => 'Произошла ошибка при отправки письма для сброса пароля',
    'Are you sure you want to delete this record?' => 'Вы уверены, что хотите удалить эту запись?',
    'Are you sure you want to delete this records?' => 'Вы уверены, что хотите удалить эти записи?',
    'Bad request' => 'Неверный запрос',
    'File size must not exceed' => 'Размер файла не должен превышать',
    'Follow the link below to activate your account' => 'Перейдите по ссылке ниже, для активации вашего аккаунта',
    'Follow the link below to reset your password' => 'Перейдите по ссылке ниже, для восстановления пароля',
    'If you need help, please {email}' => 'Если вам нужна помощь, пожалуйста {email}',
    'Incorrect email or password' => 'Неверный email или пароль',
    'Incorrect file format' => 'Неверный формат файла',
    'Incorrect username or password' => 'Неверное имя пользователя или пароль',
    'Invalid link for activate account' => 'Неверная ссылка для активации аккаунта',
    'Invalid link for reset password' => 'Неверная ссылка для сброса пароля',
    'Page not found' => 'Страница не найдена',
    'Please activate your account' => 'Пожалуйста активируйте ваш аккаунт',
    'Please choose your new password' => 'Пожалуйста введите ваш новый пароль',
    'Please fill out your email. A link to reset password will be sent there' => 'Пожалуйста введите ваш email. Ссылка на сброс пароля будет отправлена на указанный адрес',
    'Please wait…' => 'Пожалуйста подождите…',
    'Please {email} and we will help' => 'Пожалуйста {email} и мы обязательно поможем',
    'Sorry, there are works, we will be back soon…' => 'Извините, идут технические работы, мы будем доступны очень скоро',
    'There is no user with such email' => 'Пользователя с таким email не существует',
    'This email address has already been taken' => 'Данный email уже занят',
    'This role has all privileges by default, it can not be deleted' => 'Эта роль имеет все привилегии по умолчанию, она не может быть удалена',
    'To complete the registration enter your email address' => 'Для завершения регистрации укажите ваш email',
    'To complete the registration process, you must activate your account' => 'Для завершения процесса регистрации необходимо активировать ваш аккаунт',
    'We sent you a letter on {email}' => 'Мы отправили вам письмо на {email}',
    'We\'ve sent you an email with instructions to reset your password' => 'Мы отправили вам письмо с инструкцией для восстановления пароля',
    'You must fill in username or email' => 'Вы должны заполнить имя пользователя или email',
    'Your account has been deleted' => 'Ваш аккаунт был удален',
    'Your account has been suspended' => 'Ваш аккаунт заблокирован',
    'Your account is activated' => 'Ваш аккаунт активирован',
    'Your account is successfully activated' => 'Ваш аккаунт успешно активирован',
    'Saved successfully' => 'Сохранено успешно',
];
