<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'File size must not exceed' => 'Размер файла не должен превышать',
    'File types' => 'Типы файлов',
    'Image size' => 'Размер картинки',
    'Incorrect email or password' => 'Неверный email или пароль',
    'Incorrect file format' => 'Неверный формат файла',
    'Incorrect username or password' => 'Неверное имя пользователя или пароль',
    'Max. file number' => 'Макс. кол-во файлов',
    'Max. file size' => 'Макc. размер файла',
    'Max. height' => 'Макc. высота',
    'Max. size of image' => 'Макc. размер картинки',
    'Max. width' => 'Макc. ширина',
    'Min. height' => 'Мин. высота',
    'Min. size of image' => 'Мин. размер картинки',
    'Min. width' => 'Мин. ширина',
    'Only latin letters' => 'Только латинские буквы',
    'Only letters, numbers, symbols _ and -' => 'Только латинские буквы, цифры, символ _ и -',
    'Set a new password' => 'Установить новый пароль',
    'There is no user with such email' => 'Пользователя с таким email не существует',
    'This email address has already been taken' => 'Данный email уже занят',
];
