<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A letter for activation was sent to {email}' => 'Письмо для активации было отправлено на {email}',
    'An error occurred while activating account' => 'Произошла ошибка при активации аккаунта',
    'An error occurred while sending a message to activate account' => 'Произошла ошибка при отправки письма для активации аккаунта',
    'An error occurred while sending a message to reset your password' => 'Произошла ошибка при отправки письма для сброса пароля',
    'Invalid link for activate account' => 'Неверная ссылка для активации аккаунта',
    'Invalid link for reset password' => 'Неверная ссылка для сброса пароля',
    'Please activate your account' => 'Пожалуйста активируйте ваш аккаунт',
    'Saved successfully' => 'Сохранено успешно',
    'To complete the registration process, you must activate your account' => 'Для завершения процесса регистрации необходимо активировать ваш аккаунт',
    'We sent you a letter on {email}' => 'Мы отправили вам письмо на {email}',
    'We\'ve sent you an email with instructions to reset your password' => 'Мы отправили вам письмо с инструкцией для восстановления пароля',
    'Your account is successfully activated' => 'Ваш аккаунт успешно активирован',
];
